# Generated by Django 5.2 on 2025-04-24 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, choices=[(140, '140 cm'), (145, '145 cm'), (150, '150 cm'), (155, '155 cm'), (160, '160 cm'), (165, '165 cm'), (170, '170 cm'), (175, '175 cm'), (180, '180 cm'), (185, '185 cm'), (190, '190 cm'), (195, '195 cm'), (200, '200 cm')], null=True)),
                ('complexion', models.CharField(blank=True, choices=[('very_fair', 'Very Fair'), ('fair', 'Fair'), ('moderate_fair', 'Moderate Fair'), ('medium', 'Medium'), ('dark', 'Dark'), ('prefer_not', 'Prefer not to say')], max_length=20, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('slim', 'Slim'), ('average', 'Average'), ('heavy', 'Heavy')], max_length=20, null=True)),
                ('physical_status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('differently_abled', 'Differently Abled')], max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('unmarried', 'Unmarried'), ('widowed', 'Widowed'), ('divorcee', 'Divorcee')], max_length=20, null=True)),
                ('family_status', models.CharField(blank=True, choices=[('lower_middle', 'Lower Middle Class'), ('middle', 'Middle Class'), ('upper_middle', 'Upper Middle Class'), ('rich', 'Rich')], max_length=20, null=True)),
                ('denomination', models.CharField(blank=True, choices=[('syrian', 'Syrian Catholic'), ('latin', 'Latin Catholic'), ('malankara', 'Malankara'), ('orthodox', 'Orthodox'), ('jacobite', 'Jacobite'), ('marthoma', 'Marthoma'), ('csi', 'CSI')], max_length=20, null=True)),
                ('parish_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parish_place', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_details', to='matrimonyapp.userprofile')),
            ],
        ),
    ]
