# Generated by Django 5.2 on 2025-04-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0003_profile_delete_userprofiledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='matrimonyapp.userprofile'),
            preserve_default=False,
        ),
    ]
