# Generated by Django 5.2 on 2025-04-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0004_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('other', 'Other')], max_length=20)),
                ('bachelors_degree', models.CharField(blank=True, choices=[('ba', 'BA (Bachelor of Arts)'), ('bsc', 'BSc (Bachelor of Science)'), ('bcom', 'BCom (Bachelor of Commerce)'), ('btech', 'BTech (Bachelor of Technology)'), ('bca', 'BCA (Bachelor of Computer Applications)')], max_length=20, null=True)),
                ('bachelors_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('bachelors_institution', models.CharField(blank=True, max_length=150, null=True)),
                ('masters_degree', models.CharField(blank=True, choices=[('ma', 'MA (Master of Arts)'), ('msc', 'MSc (Master of Science)'), ('mcom', 'MCom (Master of Commerce)'), ('mtech', 'MTech (Master of Technology)'), ('mba', 'MBA (Master of Business Administration)')], max_length=20, null=True)),
                ('masters_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('masters_institution', models.CharField(blank=True, max_length=150, null=True)),
                ('phd_field', models.CharField(blank=True, max_length=100, null=True)),
                ('phd_institution', models.CharField(blank=True, max_length=150, null=True)),
                ('other_education', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(choices=[('business', 'Business'), ('professional', 'Professional'), ('government', 'Government Service'), ('private', 'Private Sector'), ('self_employed', 'Self Employed'), ('retired', 'Retired'), ('student', 'Student'), ('not_working', 'Not Working')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('unemployed', 'Unemployed')], max_length=20)),
                ('working_country', models.CharField(max_length=50)),
                ('working_state', models.CharField(max_length=50)),
                ('working_city', models.CharField(max_length=50)),
                ('annual_income', models.CharField(choices=[('0-25000', '0 - 25,000'), ('25001-50000', '25,001 - 50,000'), ('50001-75000', '50,001 - 75,000'), ('75001-100000', '75,001 - 100,000'), ('100001-150000', '100,001 - 150,000'), ('150001+', '150,001+'), ('not_disclosed', 'Prefer not to disclose')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_professional', to='matrimonyapp.userprofile')),
            ],
        ),
    ]
