# Generated by Django 5.2 on 2025-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0005_educationprofessional'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprofessional',
            name='working_district',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
