# Generated by Django 5.2 on 2025-04-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0006_educationprofessional_working_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('SG', 'Singapore'), ('MY', 'Malaysia'), ('DE', 'Germany'), ('FR', 'France'), ('JP', 'Japan'), ('other', 'Other')], max_length=5)),
                ('native_state', models.CharField(blank=True, max_length=100, null=True)),
                ('native_city', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_code', models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'USA/Canada (+1)'), ('+44', 'UK (+44)'), ('+61', 'Australia (+61)'), ('+971', 'UAE (+971)'), ('+966', 'Saudi (+966)'), ('+65', 'Singapore (+65)'), ('+60', 'Malaysia (+60)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+81', 'Japan (+81)')], default='+91', max_length=5)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('mobile_code', models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'USA/Canada (+1)'), ('+44', 'UK (+44)'), ('+61', 'Australia (+61)'), ('+971', 'UAE (+971)'), ('+966', 'Saudi (+966)'), ('+65', 'Singapore (+65)'), ('+60', 'Malaysia (+60)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+81', 'Japan (+81)')], default='+91', max_length=5)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_profile', to='matrimonyapp.userprofile')),
            ],
        ),
    ]
