# Generated by Django 5.2 on 2025-04-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0007_additionalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCreationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(choices=[('brother', 'Brother'), ('candidate', 'Candidate'), ('father', 'Father'), ('friend', 'Friend'), ('mother', 'Mother'), ('relative', 'Relative'), ('sister', 'Sister')], max_length=20)),
                ('creator_name', models.CharField(max_length=100)),
                ('hear_about', models.CharField(choices=[('friend', 'Friend/Family'), ('social-media', 'Social Media'), ('newspaper', 'Newspaper'), ('tv', 'TV Advertisement'), ('search-engine', 'Search Engine'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creation_details', to='matrimonyapp.userprofile')),
            ],
        ),
    ]
