# Generated by Django 5.2 on 2025-04-27 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0008_profilecreationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brides_name', models.CharField(max_length=100)),
                ('grooms_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('story', models.TextField()),
                ('cover_photo', models.CharField(max_length=255)),
                ('additional_photos', models.JSONField(default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
