# Generated by Django 5.2 on 2025-04-27 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0009_successstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='additional_photos',
        ),
        migrations.AlterField(
            model_name='successstory',
            name='cover_photo',
            field=models.ImageField(upload_to='success_stories/covers/'),
        ),
        migrations.CreateModel(
            name='AdditionalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='success_stories/additional/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('success_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='matrimonyapp.successstory')),
            ],
        ),
    ]
