# Generated by Django 5.2 on 2025-04-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0010_remove_successstory_additional_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_status', models.CharField(blank=True, choices=[('lower_middle', 'Lower Middle Class'), ('middle', 'Middle Class'), ('upper_middle', 'Upper Middle Class'), ('rich', 'Rich'), ('affluent', 'Affluent')], max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_housename', models.CharField(blank=True, max_length=100, null=True)),
                ('father_native_place', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('business', 'Business'), ('professional', 'Professional'), ('government', 'Government Service'), ('private', 'Private Sector'), ('retired', 'Retired'), ('homemaker', 'Homemaker'), ('expired', 'Expired')], max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_housename', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_native_place', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('business', 'Business'), ('professional', 'Professional'), ('government', 'Government Service'), ('private', 'Private Sector'), ('retired', 'Retired'), ('homemaker', 'Homemaker'), ('expired', 'Expired')], max_length=20, null=True)),
                ('no_of_brothers', models.PositiveIntegerField(default=0)),
                ('no_of_brothers_married', models.PositiveIntegerField(default=0)),
                ('no_of_brothers_unmarried', models.PositiveIntegerField(default=0)),
                ('no_of_brothers_priest', models.PositiveIntegerField(default=0)),
                ('no_of_sisters', models.PositiveIntegerField(default=0)),
                ('no_of_sisters_married', models.PositiveIntegerField(default=0)),
                ('no_of_sisters_unmarried', models.PositiveIntegerField(default=0)),
                ('no_of_sisters_nun', models.PositiveIntegerField(default=0)),
                ('no_of_sisters_candidate', models.PositiveIntegerField(default=0)),
                ('asset_details', models.TextField(blank=True, null=True)),
                ('about_family', models.TextField(blank=True, null=True)),
                ('family_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('family_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('family_address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='matrimonyapp.userprofile')),
            ],
        ),
    ]
