# Generated by Django 5.2 on 2025-04-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0011_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbiesAndLifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('favorite_music', models.TextField(blank=True, null=True)),
                ('preferred_books', models.TextField(blank=True, null=True)),
                ('preferred_movies', models.TextField(blank=True, null=True)),
                ('sports_games', models.TextField(blank=True, null=True)),
                ('favorite_cuisine', models.TextField(blank=True, null=True)),
                ('spoken_languages', models.TextField(blank=True, null=True)),
                ('cultural_background', models.TextField(blank=True, null=True)),
                ('eating_habits', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('eggetarian', 'Eggetarian'), ('non-vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('jain', 'Jain')], max_length=20, null=True)),
                ('drinking_habits', models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly')], max_length=20, null=True)),
                ('smoking_habits', models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='matrimonyapp.userprofile')),
            ],
        ),
    ]
