# Generated by Django 5.2 on 2025-04-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0012_hobbiesandlifestyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveIntegerField(default=31)),
                ('max_age', models.PositiveIntegerField(default=36)),
                ('min_height', models.PositiveIntegerField(default=138)),
                ('max_height', models.PositiveIntegerField(default=148)),
                ('complexion', models.CharField(choices=[('very_fair', 'Very Fair'), ('fair', 'Fair'), ('moderate_fair', 'Moderate Fair'), ('medium', 'Medium'), ('dark', 'Dark'), ('prefer_not', 'Prefer not to say'), ('any', 'Any')], default='any', max_length=20)),
                ('body_type', models.CharField(choices=[('slim', 'Slim'), ('average', 'Average'), ('heavy', 'Heavy'), ('any', 'Any')], default='any', max_length=20)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('widowed', 'Widowed'), ('divorcee', 'Divorcee'), ('any', 'Any')], default='unmarried', max_length=20)),
                ('physical_status', models.CharField(choices=[('normal', 'Normal'), ('differently_abled', 'Differently Abled'), ('any', 'Any')], default='normal', max_length=20)),
                ('family_status', models.CharField(choices=[('lower_middle', 'Lower Middle Class'), ('middle', 'Middle Class'), ('upper_middle', 'Upper Middle Class'), ('rich', 'Rich'), ('any', 'Any')], default='any', max_length=20)),
                ('religion', models.CharField(default='Christian', max_length=20)),
                ('denomination', models.CharField(choices=[('syrian', 'Syrian Catholic'), ('latin', 'Latin Catholic'), ('malankara', 'Malankara'), ('orthodox', 'Orthodox'), ('jacobite', 'Jacobite'), ('marthoma', 'Marthoma'), ('csi', 'CSI'), ('any', 'Any')], default='any', max_length=20)),
                ('education', models.CharField(choices=[('any', 'Any'), ('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD/Doctorate')], default='any', max_length=20)),
                ('occupation', models.CharField(default='Any', max_length=100)),
                ('employment_category', models.CharField(choices=[('any', 'Any'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('not_working', 'Not Working')], default='any', max_length=20)),
                ('annual_income', models.CharField(choices=[('any', 'Any'), ('0-25000', '0 - 25,000'), ('25001-50000', '25,001 - 50,000'), ('50001-75000', '50,001 - 75,000'), ('75001-100000', '75,001 - 100,000'), ('100001+', '100,001+')], default='any', max_length=20)),
                ('working_country', models.CharField(default='Any', max_length=100)),
                ('native_country', models.CharField(default='Any', max_length=100)),
                ('expectations', models.TextField(blank=True, default='Not Mentioned', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to='matrimonyapp.userprofile')),
            ],
        ),
    ]
