# Generated by Django 5.2 on 2025-04-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0014_userprofile_about_me_userprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='landline_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='permanent_address_type',
            field=models.CharField(choices=[('same', 'Same as Communication'), ('different', 'Different')], default='same', max_length=10),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='preferred_contact_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='present_address_type',
            field=models.CharField(choices=[('same', 'Same as Communication'), ('different', 'Different')], default='same', max_length=10),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='secondary_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
