# Generated by Django 5.2 on 2025-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0015_additionalprofile_alternate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalprofile',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='present_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='additionalprofile',
            name='present_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='additionalprofile',
            name='permanent_address_type',
            field=models.CharField(choices=[('same', 'Same as Communication Address'), ('different', 'Different Address')], default='same', max_length=10),
        ),
        migrations.AlterField(
            model_name='additionalprofile',
            name='present_address_type',
            field=models.CharField(choices=[('same', 'Same as Communication Address'), ('different', 'Different Address')], default='same', max_length=10),
        ),
    ]
