# Generated by Django 5.2 on 2025-04-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0016_additionalprofile_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalprofile',
            name='secondary_mobile_code',
            field=models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'USA/Canada (+1)'), ('+44', 'UK (+44)'), ('+61', 'Australia (+61)'), ('+971', 'UAE (+971)'), ('+966', 'Saudi (+966)'), ('+65', 'Singapore (+65)'), ('+60', 'Malaysia (+60)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+81', 'Japan (+81)')], default='+91', max_length=5),
        ),
    ]
