# Generated by Django 5.2 on 2025-04-29 16:02

import django.db.models.deletion
import matrimonyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0017_additionalprofile_secondary_mobile_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=matrimonyapp.models.user_profile_picture_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='matrimonyapp.userprofile')),
            ],
        ),
    ]
