# Generated by Django 5.2 on 2025-05-02 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0021_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='matrimonyapp.userprofile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='matrimonyapp.userprofile')),
            ],
            options={
                'verbose_name': 'Blocked Profile',
                'verbose_name_plural': 'Blocked Profiles',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.DeleteModel(
            name='PartnerPreference',
        ),
    ]
