# Generated by Django 5.2 on 2025-05-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0022_block_delete_partnerpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortlisted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='matrimonyapp.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlister', to='matrimonyapp.userprofile')),
            ],
            options={
                'verbose_name': 'Shortlisted Profile',
                'verbose_name_plural': 'Shortlisted Profiles',
                'unique_together': {('user', 'shortlisted_user')},
            },
        ),
    ]
