# Generated by Django 5.2 on 2025-05-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0023_shortlistedprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='interest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
