# Generated by Django 5.2 on 2025-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0024_alter_interest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Profile Picture', 'verbose_name_plural': 'Profile Pictures'},
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
