# Generated by Django 5.2 on 2025-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0025_alter_profilepicture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepicture',
            options={},
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='analysis_data',
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
