# Generated by Django 5.2 on 2025-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0026_alter_profilepicture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalphoto',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='cover_photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
