# Generated by Django 5.2 on 2025-05-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0027_alter_additionalphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.userprofile'),
        ),
    ]
