# Generated by Django 5.2 on 2025-05-06 07:34

import django.db.models.deletion
import matrimonyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0028_alter_profilepicture_options_profilepicture_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepicture',
            options={},
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='gender',
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(upload_to=matrimonyapp.models.user_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='matrimonyapp.userprofile'),
        ),
    ]
